name: quickjs

on:
  [push]
jobs:
  windows:
    name: windows
    runs-on: windows-latest
    if: "contains(toJSON(github.event.commits.*.message), '[build windows]')"
    steps:
    - uses: actions/checkout@v2
      name: Checkout project
    - uses: actions/setup-java@v1
      with:
        java-version: 11
        java-package: jdk
        architecture: x64
    - name: Build
      run: |
         cd native
         ./build.bat
    - name: Test
      run: |
         mvn --no-transfer-progress -q -B -DskipTests package
         mvn --no-transfer-progress test
    - name: Archive library
      uses: actions/upload-artifact@v1
      with:
        name: quickjs-windows
        path: src\main\resources\META-INF\quickjs.dll
  mac:
    name: macos
    runs-on: macos-10.15
    if: "contains(toJSON(github.event.commits.*.message), '[build macos]')"
    steps:
    - uses: actions/checkout@v2
      name: Checkout project
    - uses: actions/setup-java@v1
      with:
        java-version: 11
        java-package: jdk
        architecture: x64
    - name: Build
      run: |
         mkdir -p src/main/resources/META-INF
         cd native
         mkdir build
         cd build
         cmake .. -DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++ -DCMAKE_BUILD_TYPE=Release
         make
         otool -L libquickjs.dylib
         cp libquickjs.dylib ../../src/main/resources/META-INF
    - name: Test
      run: |
         mvn --no-transfer-progress -q -B -DskipTests package
         mvn --no-transfer-progress test
    - name: Archive library
      uses: actions/upload-artifact@v1
      with:
        name: quickjs-macos
        path: src/main/resources/META-INF/libquickjs.dylib
  linux:
    name: linux
    runs-on: ubuntu-16.04
    if: "contains(toJSON(github.event.commits.*.message), '[build linux]')"
    steps:
    - uses: actions/checkout@v2
      name: Checkout project
    - uses: actions/setup-java@v1
      with:
        java-version: 11
        java-package: jdk
        architecture: x64
    - name: Build
      run: |
         mkdir -p src/main/resources/META-INF
         cd native
         mkdir build
         cd build
         cmake .. -DCMAKE_C_COMPILER=gcc-9 -DCMAKE_CXX_COMPILER=g++-9 -DCMAKE_BUILD_TYPE=Release
         make
         ldd libquickjs.so
         cp libquickjs.so ../../src/main/resources/META-INF
    - name: Test
      run: |
         mvn --no-transfer-progress -q -B -DskipTests package
         mvn --no-transfer-progress test
    - name: Archive library
      uses: actions/upload-artifact@v1
      with:
        name: quickjs-linux
        path: src/main/resources/META-INF/libquickjs.so